### ISSUE TITLE
cors issues when using this in production

### ISSUE THREAD

**Issue by barbalex** [graphile-contrib/pg-order-by-related#14]
When I add `pg-order-by-related` in production I get cors issues which prevent _any_ api call because my api is located at api.apflora.ch and the app at apflora.ch. This happens even though I added the `--cors` option:

```
pm2 start ./node_modules/.bin/postgraphile -- -c postgres://user:secret@localhost:5432/apflora --append-plugins postgraphile-plugin-connection-filter,@graphile-contrib/pg-order-by-related --jwt-token-identifier auth.jwt_token --default-role anon --jwt-secret secret -s apflora --cors --disable-query-log --enable-query-batching
```

What could I be doing wrong?

**Comment by benjie** [comment]
I can't see any reason why pg-order-by-related would mess with CORS, so I suspect the error relates to CLI parsing woes. Do you get the same issue if you run `postgraphile` directly, without `pm2`?

**Comment by barbalex** [comment]
> Do you get the same issue if you run postgraphile directly, without pm2

Then I get: 

```
A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

error: password authentication failed for user "alex"
    at Connection.parseE (/home/alex/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/home/alex/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/home/alex/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
``` 

and I get that whether I append pg-order-by-related or not

**Comment by barbalex** [comment]
So this here works:

```
pm2 start ./node_modules/.bin/postgraphile -- -c postgres://user:secret@localhost:5432/apflora --append-plugins postgraphile-plugin-connection-filter --jwt-token-identifier auth.jwt_token --default-role anon --jwt-secret secret -s apflora --cors --disable-query-log --enable-query-batching
```

this here causes cors errors:
```
pm2 start ./node_modules/.bin/postgraphile -- -c postgres://user:secret@localhost:5432/apflora --append-plugins postgraphile-plugin-connection-filter,@graphile-contrib/pg-order-by-related --jwt-token-identifier auth.jwt_token --default-role anon --jwt-secret secret -s apflora --cors --disable-query-log --enable-query-batching
```
and this here causes password authentication failure:
```
npx postgraphile -- -c postgres://user:secret@localhost:5432/apflora --append-plugins postgraphile-plugin-connection-filter,@graphile-contrib/pg-order-by-related --jwt-token-identifier auth.jwt_token --default-role anon --jwt-secret secret -s apflora --cors --disable-query-log --enable-query-batching
```

**Comment by benjie** [comment]
In the last one the `--` is making all of your CLI options be ignored.

Is this an issue with Docker and commas I wonder? Try wrapping the plugin list in quotes. Try moving the plugin list to the end.

**Comment by barbalex** [comment]
O.k., I now tried removing the `--`:
```
./node_modules/.bin/postgraphile -c postgres://user:secret@localhost:5432/apflora --append-plugins postgraphile-plugin-connection-filter,@graphile-contrib/pg-order-by-related --jwt-token-identifier auth.jwt_token --default-role anon --jwt-secret secret -s apflora --cors --disable-query-log --enable-query-batching
```

and get
```
Failed to load plugin '@graphile-contrib/pg-order-by-related'
/home/alex/node_modules/postgraphile/build/postgraphile/cli.js:235
            throw e;
            ^

Error: Cannot find module '@graphile-contrib/pg-order-by-related'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at names.map.rawName (/home/alex/node_modules/postgraphile/build/postgraphile/cli.js:230:20)
    at Array.map (<anonymous>)
    at loadPlugins (/home/alex/node_modules/postgraphile/build/postgraphile/cli.js:222:18)
    at Object.<anonymous> (/home/alex/node_modules/postgraphile/build/postgraphile/cli.js:298:35)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
```

So I scratched behind my head and repeated multiple times:
```
npm i -s @graphile-contrib/pg-order-by-related
```
but when looking into the node_modules folder it never seems to get installed.

So it turned out it had never been installed correctly and it only worked when using `sudo`.

And now after this pg-order-by-related causes no cors issues any more.

Sorry for bugging you with my nooby npm issues.

And thanks for great help.

**Comment by benjie** [comment]
Glad you figured it out; thanks for letting me know the solution 👍
