### ISSUE TITLE
Naming conflict for unique reference to same table

### ISSUE THREAD

**Issue by evolkmann** [graphile-contrib/pg-order-by-related#26]
I'm submitting a ... 

* [ ] bug report
* [ ] feature request
* [x] question 

Versions:

```
Postgres (via Docker): 12.2

"postgraphile": "4.7.0",
"@graphile-contrib/pg-order-by-related": "1.0.0-beta.6"
```

## Explanation of the issue

The Issue occurs when using the `@graphile-contrib/pg-order-by-related` plugin with a `unique` reference to the same table, as you can see in the SQL below. My original usecase for this is to ensure that one row can only be once made the `parent` of another one, to force a linear structure instead of a tree structure (I am aware that this does not cover circular references, but I plan to handle this with a trigger).

I am not sure if this is a bug in the plugin or somewhere else in the postgraphile ecosystem or if I am just using the wrong data structure for my use case.

*Minimal SQL file that can be loaded into a clean database:*

```sql
create schema demo;

create table demo.unique_ref_order_by (
  id serial primary key,
  parent int unique references demo.unique_ref_order_by(id)
);

-- These two comments are necessary even without this plugin. I added them exactly as the log recommended and it solved the naming conflict.
COMMENT ON CONSTRAINT "unique_ref_order_by_parent_fkey" ON "demo"."unique_ref_order_by" IS E'@fieldName newNameHere1';
COMMENT ON CONSTRAINT "unique_ref_order_by_parent_fkey" ON "demo"."unique_ref_order_by" IS E'@foreignSingleFieldName newNameHere2';
```

Now, try to generate a GraphQL Schema using the following config:

```ts
import { postgraphile } from 'postgraphile';

postgraphile(
    {
        host: process.env.PG_HOST,
        port: Number(process.env.PG_PORT),
        database: process.env.PG_DATABASE,
        user: process.env.PG_USERNAME,
        password: process.env.PG_PASSWORD,
        ssl: process.env.PG_SSL !== 'false',
    },
    'demo',
    {
        exportGqlSchemaPath: "schema/schema.graphql",
        appendPlugins: [
            require("@graphile-contrib/pg-order-by-related")
        ],
    }
)
```

The following error is logged. When I add the suggested smart comment(s), the issue is not resolved.

```
$ ts-node -r dotenv/config ./scripts/generate-graphql-schema.ts
A serious error occurred when building the initial schema. Exiting because `retryOnInitFail` is not set. Error details:

Error: A naming conflict has occurred - two entities have tried to define the same key 'UNIQUE_REF_ORDER_BY_BY_PARENT__ID_ASC'.

  The first entity was:

    Adding ascending orderBy enum value for column "id" on table "demo"."unique_ref_order_by". You can rename this field with:
    
      COMMENT ON COLUMN "demo"."unique_ref_order_by"."id" IS E'@name newNameHere';

  The second entity was:

    Adding ascending orderBy enum value for column "id" on table "demo"."unique_ref_order_by". You can rename this field with:
    
      COMMENT ON COLUMN "demo"."unique_ref_order_by"."id" IS E'@name newNameHere';
    at Object.extend (/Users/enzovolkmann/Projekte/ostr-baustellen-planer/packages/database/node_modules/graphile-build/src/extend.js:33:13)
    at /Users/enzovolkmann/Projekte/ostr-baustellen-planer/packages/database/node_modules/@graphile-contrib/pg-order-by-related/index.js:488:25
    at Array.reduce (<anonymous>)
    at hook (/Users/enzovolkmann/Projekte/ostr-baustellen-planer/packages/database/node_modules/@graphile-contrib/pg-order-by-related/index.js:487:9)
    at SchemaBuilder.applyHooks (/Users/enzovolkmann/Projekte/ostr-baustellen-planer/packages/database/node_modules/graphile-build/src/SchemaBuilder.js:394:20)
    at Object.newWithHooks (/Users/enzovolkmann/Projekte/ostr-baustellen-planer/packages/database/node_modules/graphile-build/src/makeNewBuild.js:805:34)
    at forEach (/Users/enzovolkmann/Projekte/ostr-baustellen-planer/packages/database/node_modules/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js:25:9)
    at Array.forEach (<anonymous>)
    at hook (/Users/enzovolkmann/Projekte/ostr-baustellen-planer/packages/database/node_modules/graphile-build-pg/src/plugins/PgConnectionArgOrderBy.js:18:40)
    at SchemaBuilder.applyHooks (/Users/enzovolkmann/Projekte/ostr-baustellen-planer/packages/database/node_modules/graphile-build/src/SchemaBuilder.js:394:20)
```

*Expected behavior:*

- The issue should be solved by adding the suggested smart comments, or
- I could somehow exclude this relationship from the plugin as a workaround

-----

Thanks for having a look :)

**Comment by charlescrain** [comment]
Second this issue

**Comment by benjie** [comment]
Hi @evolkmann your issue is the second COMMENT statement overwrites the first. You need to combine the values by putting them in the same comment separated by a newline (LF only, not CRLF).

**Comment by evolkmann** [comment]
Hi @benjie, thank you. Yes that makes sense... looking back at it now I wonder why I thought both comments would persist correctly. I could have just looked at the result in the DB ..

Thanks again and sorry for this kind of obvious issue!

**Comment by benjie** [comment]
No worries; sorry I missed it before :+1:

**Comment by charlescrain** [comment]
@benjie thanks!
