### ISSUE TITLE
Error when attempting order-by-related on UUID based relations

### ISSUE THREAD

**Issue by LrWm3** [graphile-contrib/pg-order-by-related#35]
Great plugin idea!

Tried it out with 'UUID' primary keys and was seeing the error below: 

```
{
  "errors": [
    {
      "hint": "No operator matches the given name and argument types. You might need to add explicit type casts.",
      "errcode": "42883",
      "extensions": {
        "exception": {
          "hint": "No operator matches the given name and argument types. You might need to add explicit type casts.",
          "errcode": "42883"
        }
      },
      "message": "operator does not exist: uuid = character varying",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "foo"
      ],
      "stack": "error: operator does not exist: uuid = character varying\n    at Parser.parseErrorMessage (/usr/local/lib/node_modules/postgraphile/node_modules/pg-protocol/dist/parser.js:278:15)\n    at Parser.handlePacket (/usr/local/lib/node_modules/postgraphile/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/usr/local/lib/node_modules/postgraphile/node_modules/pg-protocol/dist/parser.js:39:38)\n    at Socket.<anonymous> (/usr/local/lib/node_modules/postgraphile/node_modules/pg-protocol/dist/index.js:10:42)\n    at Socket.emit (node:events:378:20)\n    at addChunk (node:internal/streams/readable:313:12)\n    at readableAddChunk (node:internal/streams/readable:288:9)\n    at Socket.Readable.push (node:internal/streams/readable:227:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)"
    }
  ],
  "data": {
    "foo": null
  }
}
```

**Comment by LrWm3** [comment]
Realized I was not including what I was sorting on in my query.

**Comment by LrWm3** [comment]
Actually, I am not totally sure why this didn't work, but I am unable to reproduce it now.
